### ISSUE TITLE
Support images copy

### ISSUE THREAD

**Issue by maiste** [ocurrent/ocurrent.org#15]
## Background

The current system only supports copying files. This feature would require tweaking the system and the configuration to be able to move images between the various elements.

## Outcome

The `YAML` file will support image copy by adding a data field:
```yaml
files:
  - [...]
data:
  -  src: "doc/dev.md"
     dst: "content/docs/ocurrent/local.md"
```
